### ISSUE TITLE
Long execution time

### ISSUE THREAD

**Issue by michaelharrer** [profitbricks/profitbricks-sdk-ruby#1]
Hi there, 
im playing around with the profitbricks-sdk-ruby and it seems pretty awesome.
A problem I am running into is the extremely long execution time, when i create my datacenter (its not too big: round about 10 servers, 2 lans, 20 volumes,... . 
I think it is because every resource is created in a sequence (the version is about 38 after the script finishes) and there is no parallel execution.
When i use the DCD the ressources are built concurrently, the versioncounter is 1 after first provisioning.
Is there any possibility to support concurrency?

Best regards,
Michael

**Comment by edevenport** [comment]
Hello @michaelharrer 

Thank you for trying out the profitbricks-sdk-ruby library and providing some input. I appreciate your interest in the project.

I could be mistaken, but I don't believe the DCD itself uses the REST API which the profitbricks-sdk-ruby library uses. So the single DCD provision event followed by the version count of 1 is not likely possible using the REST API or the Ruby library.

That said, the sequence of resource creation does add significant time when building a complex environment. The REST API is supposed to allow a server and associated resources be created/attached with a single request, but I ran into issues around this behavior when initially coding the library. I'm not sure if this was due to a bug or the lack of documentation at the time. Therefore, I decided to skip this feature for the 1.0 release and revisit at a later date.

Now I guess it is time to revisit that feature. I'll allocate some time this week to research and test that behavior through the REST API. If it can be accomplished successfully, then I'll see about adding the feature to the library. I can't account for the backend provisioning times, but it should speed up the process a bit. Then we can start testing parallel calls of that request, however, the parallel calls might be better left in the client code rather than the profitbricks-sdk-ruby library itself.

I'll keep this ticket open and add notes as I make progress.

Thank you,
Ethan

**Comment by michaelharrer** [comment]
Hi ethan,

thanks for the reply!
An option could be a "create_from_json" option in server, so we can use attach-create?

**Comment by edevenport** [comment]
Hi @michaelharrer 

I have tested the proper JSON for composite servers through a REST request and it appears to work properly now. A raw "create_from_json" option would work and having that available is probably a good idea to work around any limitations in the library. However, I would also like a friendlier method as the JSON is a bit lengthy for a fully functional server (server, attached volume, connected, NIC, an optional firewall rule). The below example JSON seems to create a fully functional server.

```
{
    "properties": {
        "name": "server1",
        "ram": 2048,
        "cores": 1
    },
    "entities": {
        "volumes": {
            "items": [
                {
                    "properties": {
                        "size": 10,
                        "name": "volume1",
                        "image": "78f51e86-3805-11e5-895c-52540066fee9",
                        "bus": "VIRTIO",
                        "imagePassword": "stackpointcloud2015"
                    }
                }
            ]
        },
        "nics": {
            "items": [
                {
                    "properties": {
                        "name": "nic1",
                        "lan": 1
                    },
                    "entities": {
                        "firewallrules": {
                            "items": [
                                {
                                    "properties": {
                                        "name": "SSH",
                                        "protocol": "TCP",
                                        "portRangeStart": 22,
                                        "portRangeEnd": 22
                                    }
                                }
                            ]
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by edevenport** [comment]
Hi @michaelharrer,

I released a new version of the profitbricks-sdk-ruby gem. The server create method now accepts volumes, NICs, and NIC firewall rules along with the server properties. This should provision a composite server that includes the additional entities in a single request. I updated the docs to reflect this behavior, but here is a quick example:

```
volumes = [ {name: 'server1-os', size: 10, image: '4dc4585c-505a-11e5-bfc6-52540066fee9', bus: 'VIRTIO', imagePassword: 'stackpointcloud2015'}, {name: 'server1-data', size: 5, bus: 'VIRTIO', licenceType: 'UNKNOWN'} ]
fwrules = [ {name: 'SSH', protocol: 'TCP', portRangeStart: 22, portRangeEnd: 22 } ]
nics = [ {name: 'public', lan: 1, firewallrules: fwrules }, {name: 'private', lan: 2 } ]

datacenter = Datacenter.get('825dee89-659a-492f-89b3-2ad5be27edee')
server = datacenter.create_server(name: 'server1', cores: 1, ram: 1024, volumes: volumes, nics: nics)
```

The extra entities are passed as a collection of hashes along with the associated resource properties. Feel free to give it a try and let me know if you encounter any issues.

Thank you,
Ethan

**Comment by edevenport** [comment]
@michaelharrer - If you want to experiment with concurrency:

**Multiple processes**

``` ruby
datacenter = Datacenter.create(name: 'Ruby SDK', location: 'us/lasdev')
datacenter.wait_for { ready? }

volumes = [ {name: 'system', size: 10, image: '6148aede-505a-11e5-bfc6-52540066fee9', bus: 'VIRTIO', imagePassword: 'stackpointcloud2015'} ]
fwrules = [ {name: 'SSH', protocol: 'TCP', portRangeStart: 22, portRangeEnd: 22} ]
nics = [ {name: 'public', lan: 1, firewallrules: fwrules} ]

puts Benchmark.measure {
  5.times do |i|
    fork do
      puts "Provisioning server#{i}..."
      start = Time.now
      server = datacenter.create_server(
        name: "server#{i}",
        cores: 1,
        ram: 1024,
        volumes: volumes,
        nics: nics
      )
      server.wait_for(1200) { ready? }
      finish = Time.now
      puts "Server #{server.properties['name']} provisioned in #{finish - start} seconds."
    end
  end
  Process.waitall
}
```

**Multi-threaded**

``` ruby
puts Benchmark.measure {
  5.times do |i|
    threads << Thread.new do
      puts "Provisioning server#{i}..."
      start = Time.now
      server = datacenter.create_server(
        name: "server#{i}",
        cores: 1,
        ram: 1024,
        volumes: volumes,
        nics: nics
      )
      server.wait_for(1200) { ready? }
      finish = Time.now
      puts "Server #{server.properties['name']} provisioned in #{finish - start} seconds."
    end
  end
  threads.map(&:join)
}
```

**Comment by michaelharrer** [comment]
Hi Ethan,

first of all thank you _very_ much for the work.
Seems all very valid and is definitely a progress in comparison to the first version (in my opinion).
Unfortunately you are right with the concurrency behavior and i ran into another issue im not able to solve elegantly:
When a composite server is created by one json configuration file, i cannot support the bootvolume attribute, hence i have to update in another step.
I think this is an API design problem, because we need the volume id first?

**Comment by edevenport** [comment]
Hello Michael,

When I was testing a composite server with a single volume over the REST API, the resulting server seemed to boot successfully despite the bootVolume not being defined. I tried this several times and it seems to work. Can you confirm?

I then decided to test a composite server with two volumes. If one volume automatically becomes the boot volume, then how are two volumes handled? Turns out it doesn't. The server attempted to provision, but it never became "available". I have reported this behavior with ProfitBricks and am currently waiting for a reply.

A single volume should be sufficient in most cases as additional volumes can be created/attached once the server is online. It is possible that the bootVolume would have to be defined once additional volumes are attached, but I have not tested that yet.

**Comment by michaelharrer** [comment]
Hi Ethan,

yes i can confirm it with one volume. Everything works fine here. Thanks! 

In the case of two volumes (which we need, because we work with btrfs-data-volumes for backup and synchronization), a server has to be updated with its bootvolume after creation (sadly the property-structure is correct):

``` ruby
  properties = {
      :bootVolume => {
          :id => bootvolumeId
      }
  }
  server = ProfitBricks::Server.update(properties)
```

The problem is to find the corresponding "bootvolumeId" after creation. Probably a findbootvolume-method would be the right approach? (perhaps with the volume-name?)

Best regards,
Michael

**Comment by codec** [comment]
I've also been testing some things using `profitbricks-sdk-ruby` and I'm experiencing very long execution times with just a simple (composite) create_server taking longer than 20 minutes.

I'm clueless what's going on here. Any ideas?

A sample of what I'm using:

``` ruby
datacenter = Datacenter.list.find { |dc| dc.properties['name'] == "test" }
image = Image.list.find { |img|
  img.properties['name'] == "Ubuntu-14.04-LTS-server-2015-09-01" && img.properties['location'] == datacenter.properties['location']
}

volumes = [{
  name: "test-root",
  size: 16,
  image: image.id,
  imagePassword: "test"
}]

nics = [{
  name: "test-eth0",
  lan: 1
}]

server = datacenter.create_server(name: 'test', cores: 2,  ram: 1024,
  volumes: volumes,
  nics: nics
)

server.wait_for { ready? }
```

**Comment by edevenport** [comment]
@michaelharrer I was updating the library to use the ProfitBricks REST API v2 and decided to test the composite server build with two volumes. I'm not sure if this was changed prior to v2, but it appears the first volume listed in the volumes array will become the boot volume now.

@codec The execution time is not related to the library. I suspect this is due to ProfitBricks instances being provisioned and managed as individual components.

**Comment by codec** [comment]
@edevenport I think it might be related to #5. Will try using the new gem release.
